INSERT INTO pessoa(nome,email) VALUES ('Maria','maria@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Joao Silva','joao@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Carlos Silva','carlos@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Adriana','adriana@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Karina','karina@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Carlos Marques','carlos@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Carlos Pereira','carlos@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Ana Maria','ana@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Beatriz','beatriz@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Joana','joana@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Tulio Augusto','tulio@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Augusto','augusto@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Marta','marta@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Silvio','silvio@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Washington','washington@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Teresa','teresa@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Luciano','luciano@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Fabiana','fabiana@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Fabio','fabio@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Gisele','gisele@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Larissa','larissa@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Natanael','natanael@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Meire','meire@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Ana Carolina','ana@gmail.com');
INSERT INTO pessoa(nome,email) VALUES ('Filipe','filipe@gmail.com');